### PR TITLE
WIP Docker

### PR DESCRIPTION
**Pull request by t-oster**
Hi,
this is a simple Dockerfile and docker-compose.yml so you can build a container from the current source code and run it.

You problably want to add some documentation and maybe add CI to automatically publish the container on docker-hub, but this way the installation is already a bit easier:

- copy conf.example.php to conf.php and make changes for database credentials (as in docker-compose.yml)
- docker-compose up -d

now you are up and running (http://localhost:8088)

Future Work:
- Add volumes for folders which should be preserved during updates
- Add documentation
- maybe publish docker containers for stable releases on docker-hub

### CODE REVIEW

**Comment by schorschii** [comment]
Hi, thanks for this first Dockerfile! As a Docker beginner, I have to ask how the database connection is established between the two containers. Currently, I'm stuck on the PHP error `Failed to establish database connection to localhost`. (I already added the MariaDB password from the Dockerfile into the `conf.php` before building the container.)

**Comment by t-oster** [comment]
The server name would be oco-db as specified in the docker -compose.yml

**Comment by schorschii** [comment]
Thanks for this clarification.

**Comment by schorschii** [comment]
What is the best way to make the `depot` directory writeable for the web server and preserve it during updates? I saw that the MariaDB container stores its data in `/var/lib/docker/volumes/...`.

**Comment by t-oster** [comment]
Yes the general way is to make it writeable in the dockerfile during a RUN command with chmod.
Then you can add a VOLUME command which makes it a docker volume which is preserved.
I personally add all volumes to the docker-compose file as bind-mounted in the same directory but this is more a runtime configuration.

Wir können aber auch gerne kurz telefonieren, wenn ich Dienstag aus dem Urlaub zurück bin

**Comment by schorschii** [comment]
Thanks for your effort! I'll merge it with the 1.0 release as I don't provide database upgrade SQL scripts in the beta version.

**Comment by schorschii** [comment]
I added the necessary cron jobs and made the `depot` dir persistent (for uploaded packages). Is it how I did it a good Docker practice or are there better solutions?

**Comment by t-oster** [comment]
Hi,
looks good to me

**Pull request merged**
