### PR TITLE
Create fr.php

### PR DESCRIPTION
**Pull request by lyonelf**

### CODE REVIEW

**Comment by schorschii** [comment]
What is this? A French translation file with English translations in it?!

**Comment by lyonelf** [comment]
Can you give me Master access, it ‘ll be more easy to push the file without pull everytimes

 

De : Georg ***@***.***> 
Envoyé : mardi 25 avril 2023 17:47
À : schorschii/OCO-Server ***@***.***>
Cc : Lionel-BZH ***@***.***>; Author ***@***.***>
Objet : Re: [schorschii/OCO-Server] Create fr.php (PR #27)

 

What is this? A French translation file with English translations in it?!

**Comment by schorschii** [comment]
Definitely not, that's what pull requests are for. You also don't need to pull every time... please have a look at a git tutorial.

**Comment by lyonelf** [comment]
all right. U re de boss.

And what about setup, I'm here but after that, don't understand. The line don"t show nothing


root@ocoserver:/# cat sql/*.sql | mysql oco

**Comment by schorschii** [comment]
> The line don"t show nothing
> root@ocoserver:/# cat sql/*.sql | mysql oco

Correct, this line does not produce any output.

**Comment by lyonelf** [comment]
fr.php is ready for master branch.

It rest some phrases to update but i'm waiting to see in web portal before

**Comment by lyonelf** [comment]
How to change language in the server portal?

**Comment by schorschii** [comment]
The web portal automatically selects the language based on your browser. Make sure you have the new fr.php in your "Language" folder and that your browser's language is set to French.

**Comment by lyonelf** [comment]
All right.

It’s ok for me.

Now i try to sync my LDAP users and, after a correct configuration script, i have an error 500 when i click on sync button.

 

 

Ip or dns name is the same issue

 

De : Georg ***@***.***> 
Envoyé : jeudi 27 avril 2023 12:40
À : schorschii/OCO-Server ***@***.***>
Cc : Lionel-BZH ***@***.***>; Author ***@***.***>
Objet : Re: [schorschii/OCO-Server] Create fr.php (PR #27)

 

The web portal automatically selects the language based on your browser. Make sure you have the new fr.php in your "Language" folder and that your browser's language is set to French.

**Comment by schorschii** [comment]
Please open separate issues for each question and be more verbose (e.g. append your Apache log files). The error 500 can mean anything, without more information it is impossible to provide help.

> Ip or dns name is the same issue

What do you mean with that???

**Pull request merged**
